### PR TITLE
Hello-rails-react-PR

### PR DESCRIPTION
**Pull request by mwanawabangona**
- Create a table for storing messages with 5 different greetings.
- Create an API endpoint that selects a random greetings
- Create a static view that will be the root of your app.
- Create the App component with react-router and render it in static view.
- Create the Greeting component that displays a greeting. Set it up as a route in  App component.
- Create a store, an action and a reducer that connects to  API endpont to get the random greeting.
- Display the random greeting in  Greeting component.

### CODE REVIEW

**Comment by ahmetbozaci** [comment]
# STATUS: INVALID  ❌ 


### Hello @mwanawabangona  ✋🏼 
#### You have submitted a project, that uses github flow.You should use git-flow [Requirement](https://github.com/microverseinc/curriculum-rails/blob/main/connect-frontend-frameworks/hello_world_with_react.md#:~:text=Make%20sure%20that%20you%20used%20correct%20Gitflow.)

#### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏


### Cheers and Happy coding! 💻 👏
coding


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

_Invalid Code Review Request **does not count** into the code reviews limit._

___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Comment by mwanawabangona** [comment]
@ahmetbozaci Hello,
thank you for your review, however, I had implemented the git-flow by making the Dev branch as the main branch, so I'm confused why you have invalidated my work, please clarify.

**Comment by ahmetbozaci** [comment]
> @ahmetbozaci Hello, thank you for your review, however, I had implemented the git-flow by making the Dev branch as the main branch, so I'm confused why you have invalidated my work, please clarify.

Please check the requirement. You are using Github flow. Main to another branch is GitHub flow. In git-flow,  you should use 3 branches. Main, develop, and feature.
[Github flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
[Git-flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)

**Comment by mwanawabangona** [comment]
@ahmetbozaci thank you for your clarification, and for making me a better developer. I have implemented the changes

Happy coding!!

**Review by EricMbouwe — APPROVED** [review]
Hi @mwanawabangona, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
